deployment:
  tasks:
    - export DEPLOYPATH=/home/startlet/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp assets/css/style.css $DEPLOYPATH
    - /bin/cp assets/img $DEPLOYPATH
    - /bin/cp assets/js $DEPLOYPATH
    - /bin/cp assets/vendor $DEPLOYPATH

    